GET http://localhost:3001/api/matches/501 HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMSIsInVzZXJuYW1lIjoicGx1c3RpZyIsImlhdCI6MTYxMjEwODE5MCwiZXhwIjoxNjEyMTk0NTkwfQ.EnlrVp8k5BOuZd26vFeZ-ZQFBWQrvQaPFO0ge46j5iw
