POST http://localhost:3001/api/tags/ HTTP/1.1
Content-Type: application/json

{
  "tag": "unieexe"
}

###

POST http://localhost:3001/api/users/tags/12 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiZGlyZWt0b3IiLCJpYXQiOjE2MDIyNTU2NjgsImV4cCI6MTYwMjM0MjA2OH0.qwEZ9vo_4NBDwVMigkbxfnoGXBD8ON110r_O_18xf5w

