POST http://localhost:3001/api/users/ HTTP/1.1
content-Type: application/json

{
  "lastname": "Lustig",
  "firstname": "Peter",
  "username": "plustig",
  "mail": "ok122@rvemold.com",
  "password": "Peter123"
}