DELETE http://localhost:3001/api/users/2 HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6Im5sdXN0aWciLCJpYXQiOjE2MDY3NDMwODksImV4cCI6MTYwNjgyOTQ4OX0.i8Qm_SlXiN3AjpU2qDXc6Zk_5wN0IQUti5RRy6fT5PI