GET http://localhost:3001/api/users/userVisit/501 HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMSIsInVzZXJuYW1lIjoicGx1c3RpZyIsImlhdCI6MTYxMjEyMzIxMSwiZXhwIjoxNjEyMjA5NjExfQ.PGINn1nSfuTVByUNAxHoXRDrTWvBmrSjpPPiYaEL-kg
