POST http://localhost:3001/api/users/updateUser HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJ1c2VybmFtZSI6Imxlb24iLCJpYXQiOjE2MTE1MTQ2ODgsImV4cCI6MTYxMTYwMTA4OH0.nszT8m1wVbVti0JdDzLrzvMIYSKjGn0kIq_voxOSAvg

{
    "key": "password",
    "oldPassword": "Nena1234",
    "newPassword": "Nena123"
}