POST http://localhost:3001/api/users/updateUser HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJ1c2VybmFtZSI6Imxlb24iLCJpYXQiOjE2MTE1MTM5OTksImV4cCI6MTYxMTYwMDM5OX0.SKUIXdAYtrJcWT40-d98WpK1RufUaHhtoTHs8Z0DV-M

{
    "key": "bio",
    "bio": "Cool new bio"
}