export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const GPS_SUCCESS = 'GPS_SUCCESS'
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const PROFILE_CREATION_SUCCESS = 'PROFILE_CREATION_SUCCESS';

export const PROFILE_VALIDATION_SUCCESS = 'PROFILE_VALIDATION_SUCCESS';
export const PROFILE_VALIDATION_FAIL = 'PROFILE_VALIDATION_FAIL';

export const UPDATE_NAME_SUCCESS = 'UPDATE_NAME_SUCCESS';
export const UPDATE_NAME_FAIL = 'UPDATE_NAME_FAIL';
export const UPDATE_BIO_SUCCESS = 'UPDATE_BIO_SUCCESS';
export const  UPDATE_BIO_FAIL = 'UPDATE_BIO_FAIL';
export const UPDATE_GENDER_SUCCESS = 'UPDATE_BIO_SUCCESS';
export const  UPDATE_GENDER_FAIL = 'UPDATE_BIO_FAIL';
export const UPDATE_PREFERENCE_SUCCESS = 'UPDATE_PREFERENCE_SUCCESS';
export const UPDATE_PREFERENCE_FAIL = 'UPDATE_PREFERENCE_FAIL';
export const UPDATE_MAIL_SUCCESS = 'UPDATE_MAIL_SUCCESS';
export const UPDATE_MAIL_FAIL = 'UPDATE_MAIL_FAIL';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';
export const UPDATE_TAGS_SUCCESS = 'UPDATE_TAGS_SUCCESS';
export const UPDATE_TAGS_FAIL = 'UPDATE_TAGS_FAIL';
export const UPDATE_DELETE_SUCCESS = 'UPDATE_DELETE_SUCCESS';
